version: "3.7"

services:
  web:
    image: ghcr.io/joachimhorshauge/lommeulken:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.web.rule=Host(`joachimhorshauge.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    environment:
      POSTGRES_DB: /run/secrets/postgres_db
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    deploy:
      update_config:
        order: start-first
    depends_on:
      - psql_bp

  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - "5432:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_db:
    external: true

volumes:
  psql_volume_bp:
  letsencrypt:
